/*
 */ 
static char *xpm_ball1[] = {
"24 24 4 1",
"  c None",
"X c #FFFF00",
". c #000000",
"O c #FF0000",
"         ......         ",
"      ...XXX   ...      ",
"    ..   XXX   XXX..    ",
"   .  XXX   XXX   XX.   ",
"  .   XXX   XXX   XXX.  ",
"  .   XXX   XXX   XXX.  ",
" . XXX   XXX   XXX   X. ",
" . XXX   XXX   XXX   X. ",
" . XXX   XXX   XXX   X. ",
".XX   XXX   XXX   XXX  .",
".XX   XXX   XXX   XXX  .",
".XX   XXX   XXX   XXX  .",
".  XXX   XXX   XXX   XX.",
".  XXX   XXX   XXX   XX.",
".  XXX   XXX   XXX   XX.",
" .X   XXX   XXX   XXX . ",
" .X   XXX   XXX   XXX . ",
" .X   XXX   XXX   XXX . ",
"  .XXX   XXX   XXX   .  ",
"  .XXX   XXX   XXX   .  ",
"   .XX   XXX   XXX  .   ",
"    ..XXX   XXX   ..    ",
"      ...   XXX...      ",
"         ......         ",
};

