static char *xpm_bike1[] = {
"24 24 6 1",
"  c None",
"X c #FFFFFF",
". c #000000",
"b c #0000FF",
"c c #0000FF",
"d c #999999",
"                        ",
"                        ",
"             ......     ",
"            .XXXXXX.    ",
"           .XXXXX.XX.   ",
"           .XXXXXXXX.   ",
"            .XXXXXX.    ",
"             .XX.       ",
"           .XXXX.       ",
"          .XXXX.        ",
"         .XXXX.X.       ",
"        .XXXX. .X.      ",
"       .XXXX.   .X.     ",
"      .XXXX.    ddd     ",
"       .bb.bbbbb   d    ",
"        .bb.dddddddd    ",
"   dd   d.bb.bb. d dd   ",
"  dddd d  .bb.b d dddd  ",
" dddddd   .bb. d dddddd ",
"dddddddd  .bb.d dddddddd",
"dddddddd .bb.d  dddddddd",
"dddddddd .XXX.  dddddddd",
" dddddd  .XXX.   dddddd ",
"  dddd    ...     dddd  ",
};



static char *xpm_bike2[] = {
"24 24 6 1",
"  c None",
"X c #FFFFFF",
". c #000000",
"b c #0000FF",
"c c #0000FF",
"d c #999999",
"                        ",
"                        ",
"             ......     ",
"            .XXXXXX.    ",
"           .XXXXX.XX.   ",
"           .XXXXXXXX.   ",
"            .XXXXXX.    ",
"             .XX.       ",
"           .XXXX.       ",
"          .XXXX.        ",
"         .XXXX.X.       ",
"        .XXXX. .X.      ",
"       .XXXX.   .X.     ",
"      .XXXX.... ddd     ",
"       .bbbbbbb.   d    ",
"       .bd. .bbb.ddd    ",
"   dd   db..bb.  d dd   ",
"  dddd d.b.bb. .d dddd  ",
" dddddd .XXX.d   dddddd ",
"dddddddd.XXXd   dddddddd",
"dddddddd .b...  dddddddd",
"dddddddd  ddd  .dddddddd",
" dddddd   .XXX.  dddddd ",
"  dddd    .....   dddd  ",
};


static char *xpm_bike3[] = {
"24 24 6 1",
"  c None",
"X c #FFFFFF",
". c #000000",
"b c #0000FF",
"c c #0000FF",
"d c #999999",
"                        ",
"                        ",
"             ......     ",
"            .XXXXXX.    ",
"           .XXXXX.XX.   ",
"           .XXXXXXXX.   ",
"            .XXXXXX.    ",
"             .XX.       ",
"           .XXXX.       ",
"          .XXXX.        ",
"         .XXXX.X.       ",
"        .XXXX. .X.      ",
"       .XXXX.   .X.     ",
"      .XXXX.    ddd     ",
"       .bbbbbb.    d    ",
"         d.bbbbb.ddd    ",
"   dd   d d .bbb.d dd   ",
"  dddd d  d.bb. d dddd  ",
" dddddd   .XXX.d dddddd ",
"dddddddd  .XXXd dddddddd",
"dddddddd .d...  dddddddd",
"dddddddd.Xddd  .dddddddd",
" dddddd .XXX.    dddddd ",
"  dddd   ...      dddd  ",
};



