/* XPM */
static char * xpm_car1[] = {
"50 22 4 1",
" 	c None",
"b	c #000000",
"r	c #ff0000",
",	c #ECA85C",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                     rrrrrrrrr                    ",
"                   rr         r                   ",
"                  r            r                  ",
"                 r              r                 ",
"                r                r                ",
"               r                  r               ",
"              r                    r              ",
"             r                      r             ",
"         rrrrrrrrrrrrrrrrrrrrrrrrrrrrrr           ",
"        rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr          ",
"      rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr         ",
"     rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr        ",
"    rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr       ",
"   rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr      ",
"  rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr      ",
" rrrrrrrbbbrrrrrrrrrrrrrrrrrrrrrrrrrrbbbrrrrr     ",
" rrrrrrbbbbbrrrrrrrrrrrrrrrrrrrrrrrrbbbbbrrrrr    ",
"       bbbbb                        bbbbb         ", 
"        bbb                          bbb          "};
