/*
 */ 
static char *xpm_flower1[] = {
"24 24 4 1",
"  c None",
"X c #00FF00",
". c #000000",
"r c #AA0000",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"           .            ",
"          .X.           ",
"        .XXX.           ",
"        .XXX.           ",
};



static char *xpm_flower2[] = {
"24 24 4 1",
"  c None",
"X c #00FF00",
". c #000000",
"r c #AA0000",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"           .            ",
"          .X.           ",
"          .XXX.         ",
"          .XXX.         ",
"         .XXX.          ",
"        .XXX.           ",
"        .XXX.           ",
};


static char *xpm_flower3[] = {
"24 24 4 1",
"  c None",
"X c #00FF00",
". c #000000",
"r c #AA0000",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"           .            ",
"          .X.           ",
"        .XXX.           ",
"        .XXX.           ",
"         .XXX.          ",
"          .XXX.         ",
"          .XXX.         ",
"         .XXX.          ",
"        .XXX.           ",
"        .XXX.           ",
};


static char *xpm_flower4[] = {
"24 24 4 1",
"  c None",
"X c #00FF00",
". c #000000",
"r c #AA0000",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"            .           ",
"           .X.          ",
"          .XXX.         ",
"          .XXX.         ",
"         .XXX.          ",
"        .XXX.           ",
"        .XXX.           ",
"         .XXX.          ",
"          .XXX.         ",
"          .XXX.         ",
"         .XXX.          ",
"        .XXX.           ",
"        .XXX.           ",
};


static char *xpm_flower5[] = {
"24 24 4 1",
"  c None",
"X c #00FF00",
". c #000000",
"r c #AA0000",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"          .             ",
"         .X.            ",
"        .XXX.           ",
"        .XXX.           ",
"         .XXX.          ",
"          .XXX.         ",
"          .XXX.         ",
"         .XXX.          ",
"        .XXX.           ",
"        .XXX.           ",
"         .XXX.          ",
"          .XXX.         ",
"          .XXX.         ",
"         .XXX.          ",
"        .XXX.           ",
"        .XXX.           ",
};


static char *xpm_flower6[] = {
"24 24 4 1",
"  c None",
"X c #00FF00",
". c #000000",
"r c #AA0000",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"          .             ",
"         .X.            ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"         .XXX.          ",
"         .XXX.          ",
"         .XXX.          ",
"         .XXX.          ",
"        .XXX.           ",
"        .XXX.           ",
"         .XXX.          ",
"         .XXX.          ",
"         .XXX.          ",
"         .XXX.          ",
"        .XXX.           ",
"        .XXX.           ",
};


static char *xpm_flower7[] = {
"24 24 4 1",
"  c None",
"X c #00FF00",
". c #000000",
"r c #AA0000",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"          .             ",
"         .X.            ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
};


static char *xpm_flower8[] = {
"24 24 4 1",
"  c None",
"X c #00FF00",
". c #000000",
"r c #AA0000",
"                        ",
"                        ",
"                        ",
"                        ",
"          .             ",
"         .X.            ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX. .   .     ",
"        .XXX. .  .      ",
"        .XXX. ...   .   ",
"        .XXX..XXX..     ",
"        .XXX.XXXX.      ",
"        .XXX.XXX. ..    ",
"        .XXXX....       ",
"        .XXX. .  .      ",
"        .XXX. .         ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
};


static char *xpm_flower9[] = {
"24 24 4 1",
"  c None",
"X c #00FF00",
". c #000000",
"r c #AA0000",
"                        ",
"                        ",
"                        ",
"                        ",
"          .             ",
"         .X.            ",
"        .XXX.           ",
"     .  .XXX.           ",
"  .  .  .XXX.           ",
"   .... .XXX.           ",
"   .XXX..XXX.           ",
" ...XXXX.XXX.           ",
"    .XXX.XXX.           ",
"   . ...XXXX. ...       ",
"  .  .  .XXX..XXX.      ",
"     .  .XXX.XXXX.      ",
"        .XXX.XXX.       ",
"        .XXXX....       ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
};


static char *xpm_flower10[] = {
"24 24 4 1",
"  c None",
"X c #00FF00",
". c #000000",
"r c #AA0000",
"                        ",
"                        ",
"          .             ",
"         .r.            ",
"        .rrr.           ",
"         .X.            ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"   .... .XXX.           ",
"   .XXX..XXX.           ",
"   .XXXX.XXX.           ",
"    .XXX.XXX.           ",
"     ...XXXX. ...       ",
"        .XXX..XXX.      ",
"        .XXX.XXXX.      ",
"        .XXX.XXX.       ",
"        .XXXX....       ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
};


static char *xpm_flower11[] = {
"24 24 4 1",
"  c None",
"X c #00FF00",
". c #000000",
"r c #AA0000",
"                        ",
"                        ",
"        .....           ",
"       .rrrrr.          ",
"        .rrr.           ",
"         .X.            ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"   .... .XXX.           ",
"   .XXX..XXX.           ",
"   .XXXX.XXX.           ",
"    .XXX.XXX.           ",
"     ...XXXX. ...       ",
"        .XXX..XXX.      ",
"        .XXX.XXXX.      ",
"        .XXX.XXX.       ",
"        .XXXX....       ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
};


static char *xpm_flower12[] = {
"24 24 4 1",
"  c None",
"X c #00FF00",
". c #000000",
"r c #AA0000",
"                        ",
"       .......          ",
"      .rrrrrrr.         ",
"      .rrrrrrr.         ",
"        .rrr..          ",
"         .X.            ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"   .... .XXX.           ",
"   .XXX..XXX.           ",
"   .XXXX.XXX.           ",
"    .XXX.XXX.           ",
"     ...XXXX. ...       ",
"        .XXX..XXX.      ",
"        .XXX.XXXX.      ",
"        .XXX.XXX.       ",
"        .XXXX....       ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
"        .XXX.           ",
};
