
static char *xpm_standright[] = {
"24 24 4 1",
"  c None",
"X c #FFFFFF",
". c #000000",
"b c #0000FF",
"        ......          ",
"       .XXXXXX.         ",
"      .XXXXX.XX.        ",
"      .XXXXXXXX.        ",
"       .XXXXXX.         ",
"         .XX.           ",
"        .XXXX.          ",
"        .X.XX.          ",
"        .X.XX.          ",
"        .X.XX.          ",
"        .X.XX.          ",
"        .X.XX.          ",
"        .X.XX.          ",
"         .b..           ",
"         .bb.           ",
"         .bb.           ",
"         .bb.           ",
"         .bb.           ",
"         .bb.           ",
"         .bb.           ",
"         .bb...         ",
"         .XXXXX.        ",
"         .XXXXX.        ",
"          .....         ",
};


static char *xpm_walkright1[] = {
"24 24 4 1",
"  c None",
"X c #FFFFFF",
". c #000000",
"b c #0000FF",
"        ......          ",
"       .XXXXXX.         ",
"      .XXXXX.XX.        ",
"      .XXXXXXXX.        ",
"       .XXXXXX.         ",
"         .XX.           ",
"        .XXXX.          ",
"        .XXXX.          ",
"       .X.XX.X.         ",
"       .X.XX.X..        ",
"      .X..XX..XX.       ",
"      .X..XX.XXXX.      ",
"       . .XX..XX.       ",
"         .bb. ..        ",
"         ..b.           ",
"        .b..b.          ",
"        .b..b.          ",
"       .b. .b.          ",
"       .b.  .b.         ",
"      .b.   .b.         ",
"      .b.   .b...       ",
"      .XXX. .XXX.       ",
"      .XXX. .XXX.       ",
"       ...   ...        ",
};


static char *xpm_walkright2[] = {
"24 24 4 1",
"  c None",
"X c #FFFFFF",
". c #000000",
"b c #0000FF",
"        ......          ",
"       .XXXXXX.         ",
"      .XXXXX.XX.        ",
"      .XXXXXXXX.        ",
"       .XXXXXX.         ",
"         .XX.           ",
"        .XXXX.          ",
"        .XXXX.          ",
"       .X.XX.X.         ",
"      ..X.XX.X.         ",
"     .XX. XX..X.        ",
"    .XXXX.XX..X.        ",
"     .XX..XX. .         ",
"      .. .bb.           ",
"         .b..           ",
"        .b..b.          ",
"        .b..b.          ",
"       .b. .b.          ",
"       .b.  .b.         ",
"      .b.   .b.         ",
"      .b..  .b..        ",
"      .XXX. .XXX.       ",
"      .XXX. .XXX.       ",
"       ...   ...        ",
};

