/*
 */ 
static char *xpm_police1[] = {
"24 30 8 1",
"  c None",
"X c #884488",
". c #000000",
"O c #555555",
"g c #aaaaaa",
"* c #2222ff",
"i c #440000",
"q c #ffffff",
"      ..........        ",
" .....XXXXXXXXXX.....   ",
" .XXXXXXXXXXXXXXXXXX.   ",
" .XXXXXXXXXXXXXXXXXX.   ",
" .XXXXXXXXXXXXXXXXXX.   ",
" .XOOOOOOOOOOOOOOOOX.   ",
" .XOOOOOOOOOOOOOOOOX.   ",
" .XXXXXXXXXXXXXXXXXX.   ",
" .XOXXXXXXXXXXXXXXOX.   ",
" .XOXXXXXXXXXXXXXXOX.   ",
" .XOXXXXXXXXXXXXXXOX.   ",
" .XOXXiiiiXXXXXXXXOX.   ",
" .XXXXiqqiXXX**XXXXX.   ",
" .XOXXiiiiXXXXXXXXOX.   ",
" .XOXXXXXXXXXXXXXXOX.   ",
" .XOXXXXXXXXXXXXXXOX.   ",
" .XOOOOOOOOOOOOOOXOX.   ",
" .XXOOOOOOOOOOOOOOXX.   ",
" .XOOOOOOOOOOOOOOOOX.   ",
" .XOOOOOOOOOOOOOOOOX.   ",
" .XXXXXXXXXXXXXXXXXX.   ",
" .XXXXXXXXXXXXXXXXXX.   ",
" .XXXXXXXXXXXXXXXXXX.   ",
" .XXXXXXXXXXXXXXXXXX.   ",
" .XXXXXXXXXXXXXXXXXX.   ",
" .XXXXXXXXXXXXXXXXXX.   ",
" ....................   ",
" .ggXXXXggggggXXXXgg.   ",
" .gggggggggggggggggg.   ",
" ....................   ",
};


static char *xpm_police2[] = {
"24 30 8 1",
"  c None",
"X c #884488",
". c #000000",
"O c #555555",
"g c #aaaaaa",
"* c #000044",
"i c #ff2222",
"q c #ffffff",
"      ..........        ",
" .....XXXXXXXXXX.....   ",
" .XXXXXXXXXXXXXXXXXX.   ",
" .XXXXXXXXXXXXXXXXXX.   ",
" .XXXXXXXXXXXXXXXXXX.   ",
" .XOOOOOOOOOOOOOOOOX.   ",
" .XOOOOOOOOOOOOOOOOX.   ",
" .XXXXXXXXXXXXXXXXXX.   ",
" .XOXXXXXXXXXXXXXXOX.   ",
" .XOXXXXXXXXXXXXXXOX.   ",
" .XOXXXXXXXXXXXXXXOX.   ",
" .XOXXXXXXXX****XXOX.   ",
" .XXXXXiiXXX*qq*XXXX.   ",
" .XOXXXXXXXX****XXOX.   ",
" .XOXXXXXXXXXXXXXXOX.   ",
" .XOXXXXXXXXXXXXXXOX.   ",
" .XOOOOOOOOOOOOOOXOX.   ",
" .XXOOOOOOOOOOOOOOXX.   ",
" .XOOOOOOOOOOOOOOOOX.   ",
" .XOOOOOOOOOOOOOOOOX.   ",
" .XXXXXXXXXXXXXXXXXX.   ",
" .XXXXXXXXXXXXXXXXXX.   ",
" .XXXXXXXXXXXXXXXXXX.   ",
" .XXXXXXXXXXXXXXXXXX.   ",
" .XXXXXXXXXXXXXXXXXX.   ",
" .XXXXXXXXXXXXXXXXXX.   ",
" ....................   ",
" .ggXXXXggggggXXXXgg.   ",
" .gggggggggggggggggg.   ",
" ....................   ",
};
