/*
 */ 
static char *xpm_woman[] = {
"24 24 4 1",
"  c None",
"X c #FFFFFF",
". c #000000",
"b c #0000FF",
"        ......          ",
"       .XXXXXX.         ",
"      .XX.XX.XX.        ",
"      .XXXXXXXX.        ",
"       .XXXXXX.         ",
"        ..XX..          ",
"      ..XXXXXX..        ",
"    ..XX..XX..XX..      ",
"   .XX.. .XX. ..XX.     ",
"  .X..   .XX.   ..X.    ",
"   .XX.. .XX. ..XX.     ",
"    ..XX..XX..XX..      ",
"      ..XXXXXX..        ",
"        ..XX..          ",
"       .bb..bb.         ",
"       .bb..bb.         ",
"       .bb..bb.         ",
"       .bb..bb.         ",
"       .bb..bb.         ",
"       .bb..bb.         ",
"      ..bb..bb..        ",
"     .XXXX..XXXX.       ",
"     .XXXX..XXXX.       ",
"      ....   ...        ",
};

static char *xpm_womanr[] = {
"24 24 4 1",
"  c None",
"X c #FFFFFF",
". c #000000",
"b c #FF0000",
"       .bbbbb.          ",
"       .bbXXXX.         ",
"      .bbbXX.XX.        ",
"      .bbbXXXXX.        ",
"      .bbbXXXX.         ",
"      .bb.XX.           ",
"     .bb.XXXX.          ",
"      ...X.XXX.         ",
"        .X.XXX.         ",
"        .X.XX.          ",
"        .X.XX.          ",
"        .X.XX.          ",
"        .X.XX.          ",
"         .b..           ",
"         .bb.           ",
"         .bb.           ",
"         .bb.           ",
"         .bb.           ",
"         .bb.           ",
"         .bb.           ",
"         .bb...         ",
"         .XXXXX.        ",
"         .X XXX.        ",
"          .....         ",
};


static char *xpm_womanwalkr1[] = {
"24 24 4 1",
"  c None",
"X c #FFFFFF",
". c #000000",
"b c #FF0000",
"       .bbbbb.          ",
"       .bbXXXX.         ",
"      .bbbXX.XX.        ",
"      .bbbXXXXX.        ",
"      .bbbXXXX.         ",
"      .bb.XX.           ",
"     .bb.XXXX.          ",
"      ....XXXX.         ",
"        X.XXXX          ",
"      .X..XX..X.        ",
"      .X..XX..X.        ",
"     .X. .XX. .X.       ",
"      .  .XX.  .        ",
"         .bb.           ",
"         ..b.           ",
"        .b..b.          ",
"        .b..b.          ",
"       .b. .b.          ",
"       .b.  .b.         ",
"      .b.   .b.         ",
"      .b.   .b...       ",
"      .XXX. .XXX.       ",
"      .X X. .X X.       ",
"       ...   ...        ",
};


static char *xpm_womanwalkr2[] = {
"24 24 4 1",
"  c None",
"X c #FFFFFF",
". c #000000",
"b c #FF0000",
"       .bbbbb.          ",
"       .bbXXXX.         ",
"      .bbbXX.XX.        ",
"      .bbbXXXXX.        ",
"      .bbbXXXX.         ",
"      .bb.XX.           ",
"     .bb.XXXX.          ",
"      ..XXXXXX.         ",
"       .X.XXXX.         ",
"      .X..XX..X.        ",
"      .X..XX..X.        ",
"     .X. .XX. .X.       ",
"      .  .XX.  .        ",
"         .bb.           ",
"         .b..           ",
"        .b..b.          ",
"        .b..b.          ",
"       .b. .b.          ",
"       .b.  .b.         ",
"      .b.   .b.         ",
"      .b..  .b..        ",
"      .XXX. .XXX.       ",
"      .X X. .X X.       ",
"       ...   ...        ",
};

